<?php


$title = 'Delete group';
$url   = $this->url('groups', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($groups->name) ?>" on
    "<?= $this->escapeHtml($groups->course) ?>" in
	  "<?= $this->escapeHtml($groups->year) ?>" by
	    "<?= $this->escapeHtml($groups->type) ?>" by
	    "<?= $this->escapeHtml($groups->idlecturer) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $groups->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>