<?php

$title = 'Delete form';
$url   = $this->url('forms', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($forms->name) ?>" by
    "<?= $this->escapeHtml($forms->dateadd) ?>"
    "<?= $this->escapeHtml($forms->author) ?>"
    "<?= $this->escapeHtml($forms->status) ?>"
    "<?= $this->escapeHtml($forms->idgroup) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $forms->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>
