<?php

$title = 'Edit form';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

// This provides a default CSS class and placeholder text for the artist element:
$dateadd = $form->get('dateadd');
$dateadd->setAttribute('class', 'form-control');
$dateadd->setAttribute('placeholder', 'DateAdd');

$author = $form->get('author');
$author->setAttribute('class', 'form-control');
$author->setAttribute('placeholder', 'Author');

$status = $form->get('status');
$status->setAttribute('class', 'form-control');
$status->setAttribute('placeholder', 'Status');

$groups = $form->get('groups');
$groups->setAttribute('class', 'input-checkbox mx-2');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('forms', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($dateadd) ?>
    <?= $this->formElement($dateadd) ?>
    <?= $this->formElementErrors()->render($dateadd, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($author) ?>
    <?= $this->formElement($author) ?>
    <?= $this->formElementErrors()->render($author, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($status) ?>
    <?= $this->formElement($status) ?>
    <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($groups) ?>
    <div class="form-check" >

        <?= $this->formElement($groups) ?>
        <?= $this->formElementErrors()->render($groups, ['class' => 'help-block']) ?>
    </div>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
