<?php

$title = 'Delete user';
$url   = $this->url('users', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($users->name) ?>" by
    "<?= $this->escapeHtml($users->surname) ?>"?
    "<?= $this->escapeHtml($users->email) ?>"?
    "<?= $this->escapeHtml($users->role) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $users->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>