<?php

$title = 'Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('users', ['action' => 'add']) ?>">Add new user</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Role</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($users as $user) : ?>
    <tr>
        <td><?= $this->escapeHtml($user->name) ?></td>
        <td><?= $this->escapeHtml($user->surname) ?></td>
        <td><?= $this->escapeHtml($user->email) ?></td>
        <td><?= $this->escapeHtml($user->role) ?></td>
        <td>
            <a href="<?= $this->url('users', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
            <a href="<?= $this->url('users', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>