<div class="main-section">
	<img class="img-cen" src="<?= $this->basePath('img/vote.png') ?>"/>
</div>

<div class="do">
	<div class="parallax">
		<p class="parallax_text">Stwórz ankietę w prosty i szybki sposób. Kliknij poniższy przycisk</br>i&nbsprozpocznij ankietowanie. </p>
		<div class="center">
			<button class="button"><a class="btnn" href="<?= $this->url('questions') ?>">stwórz</a></button>
		</div>
	</div>
</div>

<div class="make">

</div>