<?php
$title = 'Add new question';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$question = $form->get('name');
$question->setAttribute('class', 'form-control');
$question->setAttribute('placeholder', 'Name');

// This provides a default CSS class and placeholder text for the artist element:
$type = $form->get('type');
$type->setAttribute('class', 'form-control');
$type->setAttribute('placeholder', 'Type');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('questions', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($question) ?>
    <?= $this->formElement($question) ?>
    <?= $this->formElementErrors()->render($question, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($type) ?>
    <?= $this->formElement($type) ?>
    <?= $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();